# mkdocs.yml
site_name: HAHAHAHa
site_url: https://example.com
site_description: Пример документации на MkDocs Material
site_author: Your Name

# Тема
theme:
  name: material
  language: ru
  palette:
    primary: 'indigo'
    accent: 'pink'

# Навигация
nav:
  - Главная: index.md
  - НЕГЛАВНАЯ: ahah/i.md


## Использование

plugins:
  - search
  - header_plugin:
      target_page: 'ahah/i.md'


sitemap:
    changefreq: monthly
    priority:
        homepage: 1.0
        content: 0.5

# Расширения Markdown
markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true